import type { GeneratorControls, MoodPreset } from "@/features/generator/types";

export const MOOD_PRESETS: MoodPreset[] = [
  {
    id: "rainy-night",
    name: "Rainy Night",
    description: "Muted drums, soft keys, wet ambience.",
    bpmRange: [68, 82],
    keys: ["C", "D", "F", "G"],
    scales: ["minor", "dorian"],
    chordStyles: ["min7", "min9", "sus2"],
    drumDensity: 0.56,
    bassMotion: 0.35,
    ambienceType: "rain",
    filterAmount: 0.42,
    tapeWobble: 0.24,
    reverbWidth: 0.48,
    swing: 0.19,
    melodicComplexity: 0.3,
    fillProbability: 0.16,
    defaultDrumStyle: "sleepy",
  },
  {
    id: "coffee-shop",
    name: "Coffee Shop",
    description: "Brush-style groove, mellow warmth, room chatter.",
    bpmRange: [74, 90],
    keys: ["C", "D", "E", "G"],
    scales: ["major", "dorian"],
    chordStyles: ["maj7", "add9", "dom7"],
    drumDensity: 0.63,
    bassMotion: 0.45,
    ambienceType: "cafe",
    filterAmount: 0.28,
    tapeWobble: 0.18,
    reverbWidth: 0.41,
    swing: 0.16,
    melodicComplexity: 0.38,
    fillProbability: 0.18,
    defaultDrumStyle: "jazzHop",
  },
  {
    id: "midnight-study",
    name: "Midnight Study",
    description: "Focused and gentle with deep sub movement.",
    bpmRange: [70, 84],
    keys: ["A", "C", "E", "F"],
    scales: ["minor", "dorian"],
    chordStyles: ["min7", "sus4", "eleventh"],
    drumDensity: 0.52,
    bassMotion: 0.32,
    ambienceType: "room",
    filterAmount: 0.35,
    tapeWobble: 0.2,
    reverbWidth: 0.36,
    swing: 0.15,
    melodicComplexity: 0.26,
    fillProbability: 0.12,
    defaultDrumStyle: "minimal",
  },
  {
    id: "soft-jazz",
    name: "Soft Jazz",
    description: "Light swing, colorful chords, tiny walking bass hints.",
    bpmRange: [78, 94],
    keys: ["C", "F", "G", "A"],
    scales: ["major", "mixolydian", "dorian"],
    chordStyles: ["maj7", "dom7", "add9", "eleventh"],
    drumDensity: 0.66,
    bassMotion: 0.58,
    ambienceType: "room",
    filterAmount: 0.22,
    tapeWobble: 0.14,
    reverbWidth: 0.44,
    swing: 0.24,
    melodicComplexity: 0.42,
    fillProbability: 0.22,
    defaultDrumStyle: "jazzHop",
  },
  {
    id: "vinyl-dreams",
    name: "Vinyl Dreams",
    description: "Dusty texture and dreamy unresolved harmony.",
    bpmRange: [66, 80],
    keys: ["B", "D", "F", "G"],
    scales: ["minor", "lydian"],
    chordStyles: ["maj9", "min9", "sus2"],
    drumDensity: 0.5,
    bassMotion: 0.3,
    ambienceType: "vinyl",
    filterAmount: 0.5,
    tapeWobble: 0.34,
    reverbWidth: 0.55,
    swing: 0.2,
    melodicComplexity: 0.28,
    fillProbability: 0.14,
    defaultDrumStyle: "tapeCrunch",
  },
  {
    id: "nostalgic-tape",
    name: "Nostalgic Tape",
    description: "Crunchier transients and warm low-passed chord bed.",
    bpmRange: [72, 88],
    keys: ["A", "C", "D", "E"],
    scales: ["minor", "major"],
    chordStyles: ["maj7", "min7", "sus4"],
    drumDensity: 0.58,
    bassMotion: 0.36,
    ambienceType: "hiss",
    filterAmount: 0.56,
    tapeWobble: 0.39,
    reverbWidth: 0.34,
    swing: 0.17,
    melodicComplexity: 0.27,
    fillProbability: 0.2,
    defaultDrumStyle: "tapeCrunch",
  },
  {
    id: "sleepy-tokyo",
    name: "Sleepy Tokyo",
    description: "Neon night ambience with sparse motifs.",
    bpmRange: [64, 78],
    keys: ["C", "D", "E", "G"],
    scales: ["minor", "dorian"],
    chordStyles: ["min7", "min9", "sus2"],
    drumDensity: 0.46,
    bassMotion: 0.28,
    ambienceType: "nightCity",
    filterAmount: 0.46,
    tapeWobble: 0.3,
    reverbWidth: 0.47,
    swing: 0.21,
    melodicComplexity: 0.24,
    fillProbability: 0.1,
    defaultDrumStyle: "sleepy",
  },
  {
    id: "warm-sunset",
    name: "Warm Sunset",
    description: "Laid-back groove with brighter but soft voicings.",
    bpmRange: [76, 92],
    keys: ["C", "E", "F", "G"],
    scales: ["major", "mixolydian", "lydian"],
    chordStyles: ["maj7", "add9", "sus2"],
    drumDensity: 0.61,
    bassMotion: 0.4,
    ambienceType: "field",
    filterAmount: 0.25,
    tapeWobble: 0.12,
    reverbWidth: 0.4,
    swing: 0.15,
    melodicComplexity: 0.35,
    fillProbability: 0.18,
    defaultDrumStyle: "chillHop",
  },
  {
    id: "winter-window",
    name: "Winter Window",
    description: "Soft hush and fragile melody on frozen chords.",
    bpmRange: [62, 76],
    keys: ["C", "D", "F", "A"],
    scales: ["minor", "dorian", "lydian"],
    chordStyles: ["min9", "maj7", "sus4"],
    drumDensity: 0.48,
    bassMotion: 0.3,
    ambienceType: "rain",
    filterAmount: 0.47,
    tapeWobble: 0.27,
    reverbWidth: 0.58,
    swing: 0.22,
    melodicComplexity: 0.2,
    fillProbability: 0.13,
    defaultDrumStyle: "sleepy",
  },
  {
    id: "spacey-chill",
    name: "Spacey Chill",
    description: "Wide tails, drifting filters, and minimal hats.",
    bpmRange: [68, 86],
    keys: ["C", "D", "E", "A"],
    scales: ["dorian", "lydian", "minor"],
    chordStyles: ["maj9", "eleventh", "sus2"],
    drumDensity: 0.5,
    bassMotion: 0.34,
    ambienceType: "field",
    filterAmount: 0.38,
    tapeWobble: 0.25,
    reverbWidth: 0.65,
    swing: 0.18,
    melodicComplexity: 0.31,
    fillProbability: 0.16,
    defaultDrumStyle: "chillHop",
  },
];

export const DEFAULT_CONTROLS: GeneratorControls = {
  seed: 1337,
  bpm: 78,
  swing: 0.18,
  key: "C",
  scale: "minor",
  moodId: "rainy-night",
  drumStyle: "sleepy",
  drumSource: "sample",
  melodyDensity: "balanced",
  ambienceType: "rain",
  vinylAmount: 0.4,
  reverbAmount: 0.42,
  wowFlutter: 0.25,
  lowPassWarmth: 0.38,
  complexity: 0.34,
  loopBars: 4,
  masterVolume: 0.85,
  arrangementMinutes: 2,
  exportBars: 12,
};

export function getMoodPreset(moodId: string): MoodPreset {
  return MOOD_PRESETS.find((preset) => preset.id === moodId) ?? MOOD_PRESETS[0]!;
}

export function controlsFromMood(moodId: string, current: GeneratorControls): GeneratorControls {
  const mood = getMoodPreset(moodId);
  const bpm = Math.round((mood.bpmRange[0] + mood.bpmRange[1]) / 2);

  return {
    ...current,
    moodId: mood.id,
    bpm,
    key: mood.keys[0] ?? current.key,
    scale: mood.scales[0] ?? current.scale,
    drumStyle: mood.defaultDrumStyle,
    ambienceType: mood.ambienceType,
    swing: mood.swing,
    complexity: mood.melodicComplexity,
    lowPassWarmth: mood.filterAmount,
    wowFlutter: mood.tapeWobble,
    reverbAmount: mood.reverbWidth,
  };
}
